/*
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued
terms.
*/

function fibonacciEven(end){
    let total = 0;
    let a = 0;
    let b = 1;
    let next = 0;
    while (a <= end){
        if (a % 2 === 0){
            
            total += a
        }
        next = a+b
        a = b
        b = next
        
    }
    return total
}

console.log(fibonacciEven(4000000))